language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - coverage erase
  - coverage run app.py && coverage html

after_success:
  - codecov